[package]
name = "shared"
edition.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
reqwest.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
