[package]
name = "infrastructure"
edition.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
domain.workspace = true
async-trait.workspace = true
reqwest.workspace = true
thiserror.workspace = true
