[package]
name = "interface"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
registry.workspace = true
usecase.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
