[package]
edition.workspace = true
name = "registry"
publish.workspace = true
version.workspace = true

[dependencies]
domain.workspace = true
infrastructure.workspace = true
shared.workspace = true
usecase.workspace = true
