name: CI for frontend
on:
  push:
    branches: [main]
    paths-ignore:
      - "backend/**"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "backend/**"
      - "docs/**"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version-file: frontend/package.json
          cache-dependency-path: frontend/pnpm-lock.yaml
          cache: 'pnpm'
      - name: Dependency restore
        id: cache-restore
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: js-depend-${{ runner.os }}-${{ hashFiles('frontend/pnpm-lock.yaml') }}
      - name: Dependency installing
        run: pnpm install --frozen-lockfile
      - name: type-check
        run: pnpm run tc
      - name: lint
        run: pnpm run lint
      - name: fmt
        run: pnpm run format:check
      - name: check
        run: pnpm run check:check
