name: lint for toml and yaml
on:
  push:
    branches: [main]
    paths-ignore:
      - "**"
      - "!**/**.yaml"
      - "!**/**.yml"
      - "!**/**.toml"
  pull_request:
    paths-ignore:
      - "**"
      - "!**/**.yaml"
      - "!**/**.yml"
      - "!**/**.toml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v3
        with:
          version: 2025.11.4
          install: true
          cache: true
          experimental: false
      - name: ci
        run: mise run lint:ci
